### ISSUE TITLE
Schema is edited, but there is no data migration.

### ISSUE THREAD

**Issue by wardpenney** [ilyakatz/data-migrate#105]
Hi all,

I noticed that the `data_migrations` table gets auto-created and added to the `schema.rb` when a data migration is ran.

> when you use one of the provide rake tasks, a table called data_migrations will be created in your database

But without an actual `ActiveRecord::Migration` to create this table the lines that define `data_migrations` get removed from `schema.rb` when other developers run `rake db:migrate` without having any data migrations present.

Was there a reason to not require an explicit `ActiveRecord::Migration` to create this table?

**Comment by cabello** [comment]
I am facing the same issue, I was finally able to reproduce it.

If I run `bundle exec rake db:drop db:create db:migrate:with_data` the `db/schema.rb` remains **untouched** with `create_table "data_migrations", primary_key: "version", id: :string, force: :cascade do |t|` inside.

If I run `bundle exec rake db:drop db:create db:migrate` the `db/schema.rb` is changed and the `data_migrations` table is **removed**.

Most developers use `db:migrate` because it's the standard command for the majority of our Ruby/Rails apps.

When we had to make a gem that creates a table we also made a rake task that installs the migration, should data-migrate consider something similar? We got inspiration from [paper_trail](https://github.com/paper-trail-gem/paper_trail#1b-installation).

**Comment by jamesstonehill** [comment]
Yeah we also are getting this issue. I suggest including a rake task that can generate a migration to create this migration for you. Somewhat the devise generators. https://github.com/plataformatec/devise#getting-started

**Comment by wardpenney** [comment]
It makes sense to generate a Rails schema migration during the install process that creates the needed table. That migration causes an update to `schema.rb` and gets committed into the repository, and everyone can see it in PR review. 

It also opens up the opportunity to `drop` the table later with a subsequent migration.

**Comment by ilyakatz** [comment]
Hi folks, apologies for radio silence, I've been a bit preoccupied lately. I think it does make sense to create a migration. Would any of you fine people like to give it a try and create a PR?

**Comment by aleksandrs-ledovskis** [comment]
@ilyakatz As the issue was closed as completed, could you please point to version/commit where the fix is present?

**Comment by ilyakatz** [comment]
Hi @aleksandrs-ledovskis sorry, should have commented. No one took this one as a possible solution (This PR never completed, so I closed it out until someone else has a proposed solution.

**Comment by sabihullahmurad-10p** [comment]
> Hi @aleksandrs-ledovskis sorry, should have commented. No one took this one as a possible solution (This PR never completed, so I closed it out until someone else has a proposed solution.

just to get more clearity, is there a solution for it other than running the command 'rails db:migrate:with_data'?
