### ISSUE TITLE
Why not migrate data with regular migrations?

### ISSUE THREAD

**Issue by janko** [ilyakatz/data-migrate#142]
I've always just been doing data migrations together with schema changes (in `db/migrate`), and never had any issues with that approach. So I'm trying to understand from the README what does this gem offer that regular Active Record migrations do not already have?

**Comment by ilyakatz** [comment]
Hi @janko. there are a few reasons why you'd want to separate data and schema migrations. Some examples are

* Tests - if you have data/db intermingled, you will run both in test which may not be desirable
* Code changes - as you application grows, if your migrations use ActiveRecord objects (instead of raw sql), code may start to break because new validations were added relationships (eg. `has_many`) were removed
* Style - keep schema and data separate so it's easier to identify what was done where

There is also an article that folks at ombulabs wrote up comparing a few options

https://www.ombulabs.com/blog/rails/data-migrations/three-useful-data-migrations-patterns-in-rails.html

Of course, you don't *have to* use this gem and if it works for you in using regular rails process, sure, no need for another gem. Good to have options

**Comment by janko** [comment]
Thanks a lot for the explanation. Yeah, it's definitely good to have more options, I was just curious if there is anything I was missing in my knowledge 😃

In my migrations I re-define the portion of models I need for the data migration, for example:

```rb
class UpdatePostsState < ActiveRecord::Migration
  class Post < ActiveRecord::Base
  end

  def change
    Post.update_all(state: "published")
  end
end
```

I remember the Rails guides used to recommend this approach (and recommended against using `app/models` or anything else from your app), but I cannot find this now.

Anyway, thanks again for taking the time to answer 👍

**Comment by rwojnarowski** [comment]
> I remember the Rails guides used to recommend this approach (and recommended against using app/models or anything else from your app), but I cannot find this now.

If someone is curious, this is where you can read about it:
https://guides.rubyonrails.org/v3.2/migrations.html#using-models-in-your-migrations

**Comment by StdVectorBool** [comment]
@ilyakatz what's the project's recommended practice regarding:
> Code changes - as you application grows, if your migrations use ActiveRecord objects (instead of raw sql), code may start to break because new validations were added relationships (eg. has_many) were removed

to carry out the change @janko needs? I can't see how `data-migration` solves the problem where the latest code for Post has validators for fields that didn't exist when the Data Migration was written.  Are there sample projects demonstrating proper usage of this gem?

**Comment by ilyakatz** [comment]
Here is the blog post that the original creator wrote that explains why this gem was created http://ajvargo.com/2011/05/data_migrate/, hopefully that can help you decide.
