### ISSUE TITLE
Support for Multi-tenancy

### ISSUE THREAD

**Issue by KarmaTensel** [ilyakatz/data-migrate#210]
Hi all,
I have faced an issue where running data migration for a specific tenant does not yield me the required fields in the model. The data migration runs correctly, correctly reflected in the schema.rb and also when checked the status of the migration everything looks good. However, when i try to create a record for that table gives me `unknown attribute the-field`. So basically, the model does not have the fields introduced.

So how i ran the data migration for specific-tenant: `DB=tenant rake db:migrate:with_data`.

After migration, how i checked for the attributes in the model:
1. rails c
2. switch tenant
3. Model.attribute_names

There are no field(s) for which we ran migration.

However, when i run ` rake db:migrate:with_data` and do
1. rails c
2. Model.attribute_names

I can see the fields that i am expecting. So what happens is the migration is applied to only public schema. When i switch to a specific tenant, the changes does not seem to be there. Had me wondering about multi-tenancy support by data_migrate.

Any help is highly appreciated.

**Comment by KarmaTensel** [comment]
@ilyakatz yes, `rake db:migrate` works.

**Comment by bmulholland** [comment]
What form of multi-tenancy are you using? Based on your text, I'm assuming you're asking about schema-based tenants, where each tenant gets its own set of schema/tables within the same database -- likely using `apartment`?

**Comment by KarmaTensel** [comment]
yes @bmulholland it is `Apartment`. I tried switching between tenants and running the migration but i still don't get the results.

**Comment by bmulholland** [comment]
You'd have to look into whether data-migrate is creating a migration schema for each tenant. That's probably the issue. But TBH, Apartment is generally not recommended, even by its authors, and generally doesn't scale. [I've written about it here.](https://bmulholland.ca/for-developers/multi-tenancy-options/)

I know it would be a huge project, but I'd recommend using RLS for multi tenancy. We use https://github.com/suus-io/rls_rails and specifically our fork, which we hope to merge upstream, https://github.com/recitalsoftware/rls_rails.

FWIW, with RLS, this gem works out of the box -- though we need to explicitly choose how to run each migration. Usually that means `RLS.run_per_tenant`. Still, that means that this issue is actually "Support for Apartment" and not for multi-tenancy generally.

**Comment by KarmaTensel** [comment]
Thank you for pointing out what could possibly be the real issue and also for the suggestion. I will check out `RLS` gem for sure :)))
