### ISSUE TITLE
rexml 3 HIGH severity vulnerabilities

### ISSUE THREAD

**Issue by dimitrisdovinos** [ilyakatz/data-migrate#350]
We are picking up HIGH severity vulnerabilities from rexml 3.2.6 https://github.com/advisories/GHSA-rwcj-7jjp-4w38, https://github.com/advisories/GHSA-5866-49gr-22v4, https://github.com/advisories/GHSA-2rxp-v6pw-ch6m.

Is it possible to raise the rexml version to 3.3.9? At that version all 3 vulnerabilities are fixed.

**Comment by Morozzzko** [comment]
Thank you for reporting that! I'll surely update rexml to fix the vulnerability.

While the fix is not out – `rexml` is not a direct dependency of `data_migrate`, and our only direct dependencies of `activerecord` and `railties` are only [constrained from the bottom](https://github.com/ilyakatz/data-migrate/blob/78716ad1b55a363d655f5bf8376c1dcba5902111/data_migrate.gemspec#L22) – `>= 6.1'`. So it should be possible to fix the issue without touching anything in the gem itself

If that's not the case for you, please share a little bit of insight how that works in your project! 

Thank you for reporting vulnerabilities. I can see it's not your first issue here, and I'm glad that you took the time to report them

**Comment by dimitrisdovinos** [comment]
Thanks for the prompt response. The production image is getting scanned via AWS Inspector. It picks up rexml  3.2.5 from the Gemfile.lock.

<img width="796" alt="image" src="https://github.com/user-attachments/assets/7efe48ee-211f-4356-99e6-fb3a289915eb">
I am running Ruby 3.3.6 and Rails 7.2.2 and I have forced railties and activerecord to 7.2.2.

I understand that this is not direct dependency.

**Comment by vprigent** [comment]
Hi @dimitrisdovinos, the last version of the gem should avoid this problem entirely as we moved the Gemfile.lock away from the packaged files.
Feel free to comment/reopen if the problem persists
